# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1173, 904)
        Form.setStyleSheet("/* ===================== 全局基础样式（亮蓝色主题） ===================== */\n"
"/* 作用：统一所有控件的基础字体、颜色和背景，保证界面风格一致 */\n"
"QWidget {\n"
"    /* 字体：优先微软雅黑，兼容Arial和无衬线字体 */\n"
"    font-family: \"Microsoft YaHei\", Arial, sans-serif;\n"
"    /* 基础字号：14px，保证可读性 */\n"
"    font-size: 14px;\n"
"    /* 文字主色：深蓝色，和亮蓝色背景对比清晰 */\n"
"    color: #192a56;\n"
"    /* 全局背景色：极浅的蓝色，打造亮蓝色主题基调 */\n"
"    background-color: #e8f4fc;\n"
"}\n"
"\n"
"/* ===================== 主标题样式（人脸识别系统） ===================== */\n"
"/* 适配控件：id为label_28的Label（顶部大标题） */\n"
"QLabel#label_28 {\n"
"    font-size: 24px;          /* 标题字号放大 */\n"
"    font-weight: bold;        /* 加粗突出 */\n"
"    color: #0a5cad;           /* 亮蓝色主题主色，醒目且清爽 */\n"
"    padding: 10px 0;          /* 上下内边距，增加间距 */\n"
"    /* 底部亮蓝色边框，强化主题且分隔标题 */\n"
"    border-bottom: 2px solid #1890ff; \n"
"    margin-bottom: 10px;      /* 底部外边距，避免和下方控件粘连 */\n"
"    background-color: #ffffff;/* 白色背景，突出标题 */\n"
"    border-radius: 8px 8px 0 0; /* 顶部圆角，和下方控件呼应 */\n"
"}\n"
"\n"
"/* ===================== 左侧功能选项GroupBox ===================== */\n"
"/* 适配控件：id为groupBox的分组框（左侧功能按钮容器） */\n"
"QGroupBox#groupBox {\n"
"    font-size: 16px;          /* 分组标题字号 */\n"
"    font-weight: bold;        /* 标题加粗 */\n"
"    color: #0a5cad;           /* 标题颜色，亮蓝色主题主色 */\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框，贴合主题 */\n"
"    border-radius: 8px;       /* 圆角，提升现代感 */\n"
"    padding-top: 20px;        /* 顶部内边距，避免标题和内容重叠 */\n"
"    margin: 5px;              /* 外边距，和其他控件保持间距 */\n"
"    background-color: #ffffff;/* 白色背景，突出功能区且提亮 */\n"
"}\n"
"\n"
"/* 分组框标题位置调整 */\n"
"QGroupBox#groupBox::title {\n"
"    subcontrol-origin: margin; /* 标题基于外边距定位 */\n"
"    left: 20px;               /* 标题右移20px，避免贴边 */\n"
"    padding: 0 10px 0 10px;   /* 标题左右内边距，避免文字和边框粘连 */\n"
"    color: #0a5cad;           /* 标题文字用主题主色 */\n"
"}\n"
"\n"
"/* ===================== 左侧核心功能按钮（亮蓝色主题） ===================== */\n"
"/* 适配控件：人脸信息录入、人脸识别、数据库管理、退出按钮 */\n"
"QPushButton#pushButton_sb_3, QPushButton#pushButton_25, \n"
"QPushButton#pushButton_gl_3, QPushButton#pushButton_lr_3 {\n"
"    font-size: 16px;          /* 按钮文字放大，突出 */\n"
"    padding: 15px 0;          /* 上下内边距，增大按钮点击区域 */\n"
"    border-radius: 8px;       /* 圆角按钮 */\n"
"    border: none;             /* 去掉默认边框 */\n"
"    background-color: #1890ff;/* 亮蓝色主题主色，清爽醒目 */\n"
"    color: white;             /* 文字白色，对比明显 */\n"
"}\n"
"\n"
"/* 功能按钮hover状态（鼠标悬浮）- 加深蓝色，保留交互反馈 */\n"
"QPushButton#pushButton_sb_3:hover, QPushButton#pushButton_25:hover, \n"
"QPushButton#pushButton_gl_3:hover {\n"
"    background-color: #0f6ebb;/* 深一级的亮蓝色，反馈交互状态 */\n"
"}\n"
"\n"
"/* 退出按钮特殊样式（主题色系内的警示色） */\n"
"QPushButton#pushButton_lr_3 {\n"
"    background-color: #ff4d6d;/* 亮粉色系，和亮蓝色对比且不突兀 */\n"
"}\n"
"\n"
"/* 退出按钮hover状态 */\n"
"QPushButton#pushButton_lr_3:hover {\n"
"    background-color: #d63756;/* 深一级粉色，强化警示且贴合亮色调 */\n"
"}\n"
"\n"
"/* ===================== 右侧功能区GroupBox（亮蓝色主题） ===================== */\n"
"/* 适配控件：人脸信息录入、人脸识别、数据库管理的分组框 */\n"
"QGroupBox#groupBox_2, QGroupBox#groupBox_3, QGroupBox#groupBox_4 {\n"
"    font-size: 16px;          /* 分组标题字号 */\n"
"    font-weight: bold;        /* 标题加粗 */\n"
"    color: #0a5cad;           /* 标题颜色，亮蓝色主题主色 */\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框，统一主题风格 */\n"
"    border-radius: 8px;       /* 圆角，统一风格 */\n"
"    padding-top: 20px;        /* 顶部内边距，避免标题和内容重叠 */\n"
"    margin: 5px;              /* 外边距，和其他控件保持间距 */\n"
"    background-color: #ffffff;/* 白色背景，提亮内容区 */\n"
"}\n"
"\n"
"/* 右侧分组框标题位置调整 */\n"
"QGroupBox#groupBox_2::title, QGroupBox#groupBox_3::title, QGroupBox#groupBox_4::title {\n"
"    subcontrol-origin: margin; /* 标题基于外边距定位 */\n"
"    left: 20px;               /* 标题右移20px */\n"
"    padding: 0 10px 0 10px;   /* 标题左右内边距 */\n"
"    color: #0a5cad;           /* 标题文字用主题主色 */\n"
"}\n"
"\n"
"/* ===================== 信息面板Frame（带边框区域） ===================== */\n"
"/* 适配控件：人脸信息面板、识别结果面板的Frame */\n"
"QFrame#frame, QFrame#frame_2 {\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框，贴合主题 */\n"
"    border-radius: 8px;       /* 圆角，统一风格 */\n"
"    background-color: #ffffff;/* 白色背景，突出信息且提亮 */\n"
"    padding: 10px;            /* 内边距，避免内容贴边 */\n"
"    /* 轻微阴影，增强层次感，不破坏亮色调 */\n"
"    box-shadow: 0 2px 4px rgba(24, 144, 255, 0.1);\n"
"}\n"
"\n"
"/* ===================== 信息面板标题Label ===================== */\n"
"/* 适配控件：人脸信息、识别结果的标题Label */\n"
"QLabel#label_29, QLabel#label_27 {\n"
"    font-size: 16px;          /* 标题字号 */\n"
"    font-weight: bold;        /* 加粗突出 */\n"
"    color: #0a5cad;           /* 标题颜色，亮蓝色主题主色 */\n"
"    padding: 10px 0;          /* 上下内边距 */\n"
"    /* 底部浅亮蓝色边框，分隔标题和内容 */\n"
"    border-bottom: 1px solid #b3d9f2;\n"
"    margin-bottom: 10px;      /* 底部外边距，避免粘连 */\n"
"}\n"
"\n"
"/* ===================== 普通按钮样式（上传、摄像头等） ===================== */\n"
"/* 适配范围：排除左侧核心功能按钮的所有普通按钮 */\n"
"QPushButton:not(#pushButton_sb_3):not(#pushButton_25):not(#pushButton_gl_3):not(#pushButton_lr_3) {\n"
"    padding: 8px 15px;        /* 内边距，适中的点击区域 */\n"
"    border-radius: 6px;       /* 圆角，比核心按钮略小 */\n"
"    border: 1px solid #1890ff;/* 亮蓝色边框，贴合主题 */\n"
"    background-color: #ffffff;/* 白色背景，提亮按钮 */\n"
"    color: #0a5cad;           /* 主题主色文字，清晰易读 */\n"
"}\n"
"\n"
"/* 普通按钮hover状态 */\n"
"QPushButton:not(#pushButton_sb_3):not(#pushButton_25):not(#pushButton_gl_3):not(#pushButton_lr_3):hover {\n"
"    background-color: #f0f7ff;/* 极浅的亮蓝色背景，反馈交互 */\n"
"    border-color: #0f6ebb;    /* 边框加深，强化hover效果 */\n"
"}\n"
"\n"
"/* ===================== 保存信息按钮特殊样式（主题色系） ===================== */\n"
"/* 适配控件：id为pushButton_26的保存按钮 */\n"
"QPushButton#pushButton_26 {\n"
"    background-color: #52c41a;/* 亮绿色，和亮蓝色搭配清爽，代表确认 */\n"
"    color: white;             /* 白色文字 */\n"
"    border: none;             /* 去掉默认边框 */\n"
"}\n"
"\n"
"/* 保存按钮hover状态 */\n"
"QPushButton#pushButton_26:hover {\n"
"    background-color: #389e0d;/* 深一级亮绿色，强化反馈 */\n"
"}\n"
"\n"
"/* ===================== 输入框样式（姓名、年龄、学号等） ===================== */\n"
"QLineEdit {\n"
"    padding: 8px 10px;        /* 内边距，输入时不贴边 */\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框，贴合主题 */\n"
"    border-radius: 6px;       /* 圆角，统一风格 */\n"
"    background-color: #ffffff;/* 白色背景，方便输入且提亮 */\n"
"    color: #0a5cad;           /* 主题主色文字，易读 */\n"
"}\n"
"\n"
"/* 输入框聚焦状态（选中输入时） */\n"
"QLineEdit:focus {\n"
"    border-color: #1890ff;    /* 亮蓝色边框，提示当前激活状态 */\n"
"    outline: none;            /* 去掉默认的外轮廓线 */\n"
"    /* 轻微发光效果，强化聚焦，贴合亮色调 */\n"
"    box-shadow: 0 0 4px rgba(24, 144, 255, 0.2);\n"
"}\n"
"\n"
"/* ===================== 单选按钮样式（性别选择） ===================== */\n"
"QRadioButton {\n"
"    padding: 5px;             /* 内边距，增大点击区域 */\n"
"    color: #0a5cad;           /* 主题主色文字 */\n"
"}\n"
"\n"
"/* 单选按钮指示器（圆形选择框）大小调整+主题色 */\n"
"QRadioButton::indicator {\n"
"    width: 16px;              /* 宽度 */\n"
"    height: 16px;             /* 高度 */\n"
"}\n"
"\n"
"/* 单选按钮选中状态指示器 */\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #1890ff;/* 亮蓝色填充，贴合主题 */\n"
"    border-color: #0f6ebb;    /* 深一点的蓝色边框 */\n"
"}\n"
"\n"
"/* ===================== 文本编辑框（识别结果） ===================== */\n"
"QPlainTextEdit#plainTextEdit_2 {\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框 */\n"
"    border-radius: 6px;       /* 圆角 */\n"
"    padding: 10px;            /* 内边距，文字不贴边 */\n"
"    background-color: #ffffff;/* 白色背景，方便阅读且提亮 */\n"
"    color: #0a5cad;           /* 主题主色文字 */\n"
"}\n"
"\n"
"/* 文本编辑框聚焦状态 */\n"
"QPlainTextEdit#plainTextEdit_2:focus {\n"
"    border-color: #1890ff;    /* 亮蓝色边框，提示激活 */\n"
"    outline: none;            /* 去掉默认外轮廓 */\n"
"}\n"
"\n"
"/* ===================== 表格样式（数据库管理） ===================== */\n"
"QTableView#tableView_2 {\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框 */\n"
"    border-radius: 6px;       /* 圆角 */\n"
"    background-color: #ffffff;/* 白色背景，提亮表格 */\n"
"    gridline-color: #e8f4fc;  /* 极浅亮蓝色网格线，不刺眼 */\n"
"    color: #0a5cad;           /* 主题主色文字 */\n"
"}\n"
"\n"
"/* 表格单元格内边距 */\n"
"QTableView#tableView_2::item {\n"
"    padding: 5px;             /* 内边距，内容不贴边 */\n"
"}\n"
"\n"
"/* 表格选中行样式（主题色） */\n"
"QTableView#tableView_2::item:selected {\n"
"    background-color: #e6f7ff;/* 极浅亮蓝色背景，突出选中行且不刺眼 */\n"
"    color: #0a5cad;           /* 主题主色文字，保持清晰 */\n"
"}\n"
"\n"
"/* 表格表头样式（亮蓝色主题） */\n"
"QHeaderView::section {\n"
"    background-color: #f0f7ff;/* 浅亮蓝色背景，区分表头 */\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框 */\n"
"    padding: 8px;             /* 内边距，文字不贴边 */\n"
"    font-weight: bold;        /* 表头文字加粗 */\n"
"    color: #0a5cad;           /* 主题主色文字 */\n"
"}\n"
"\n"
"/* ===================== 图片显示Label ===================== */\n"
"/* 适配控件：摄像头预览、人脸显示的Label */\n"
"QLabel#label_15, QLabel#label_30, QLabel#label_24 {\n"
"    border: 1px solid #b3d9f2;/* 浅亮蓝色边框，贴合主题 */\n"
"    border-radius: 6px;       /* 圆角 */\n"
"    background-color: #f0f7ff;/* 浅亮蓝色背景，图片未加载时不突兀 */\n"
"}")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_14.addWidget(self.label_28)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(150)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_sb_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_sb_3.setAutoDefault(False)
        self.pushButton_sb_3.setDefault(False)
        self.pushButton_sb_3.setFlat(False)
        self.pushButton_sb_3.setObjectName("pushButton_sb_3")
        self.verticalLayout_15.addWidget(self.pushButton_sb_3)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_15.addWidget(self.pushButton_25)
        self.pushButton_gl_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_gl_3.setObjectName("pushButton_gl_3")
        self.verticalLayout_15.addWidget(self.pushButton_gl_3)
        self.pushButton_lr_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_lr_3.setObjectName("pushButton_lr_3")
        self.verticalLayout_15.addWidget(self.pushButton_lr_3)
        self.verticalLayout_15.setStretch(0, 2)
        self.verticalLayout_15.setStretch(1, 2)
        self.verticalLayout_15.setStretch(2, 2)
        self.verticalLayout_15.setStretch(3, 2)
        self.verticalLayout.addLayout(self.verticalLayout_15)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(Form)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 891, 761))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 861, 731))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("ui/images/face_background_1.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_9.addWidget(self.label_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_12.addWidget(self.pushButton_14)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_15 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_13.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_13.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_13.addWidget(self.pushButton_17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayout_9.setStretch(0, 6)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_9.setStretch(4, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(15)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_16.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("ui/images/face_background_2.jpg"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_16.addWidget(self.label_30)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setVerticalSpacing(60)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.verticalLayout_16.addLayout(self.formLayout_3)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, 60)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_19.addWidget(self.label_34)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_19.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_6.setCheckable(True)
        self.radioButton_6.setChecked(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_19.addWidget(self.radioButton_6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_19)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_16.addWidget(self.pushButton_26)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 3)
        self.verticalLayout_16.setStretch(2, 3)
        self.verticalLayout_16.setStretch(3, 2)
        self.verticalLayout_16.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout_16)
        self.horizontalLayout_11.addWidget(self.frame)
        self.horizontalLayout_11.setStretch(0, 7)
        self.horizontalLayout_11.setStretch(1, 3)
        self.stackedWidget_2.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 891, 761))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 871, 731))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("ui/images/face_background_1.jpg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_11.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_11.addWidget(self.label_25)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_19 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_16.addWidget(self.pushButton_19)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_16.addWidget(self.lineEdit_11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_11.addWidget(self.label_26)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_20 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_17.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_17.addWidget(self.pushButton_21)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.verticalLayout_11.setStretch(0, 6)
        self.verticalLayout_11.setStretch(1, 1)
        self.verticalLayout_11.setStretch(2, 1)
        self.verticalLayout_11.setStretch(3, 1)
        self.verticalLayout_11.setStretch(4, 1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_12.addWidget(self.label_27)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_2)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_12.addWidget(self.plainTextEdit_2)
        self.verticalLayout_12.setStretch(0, 2)
        self.verticalLayout_12.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.verticalLayout_12)
        self.horizontalLayout_15.addWidget(self.frame_2)
        self.horizontalLayout_15.setStretch(0, 7)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 891, 761))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 871, 731))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(50)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 20, -1, 0)
        self.horizontalLayout_18.setSpacing(20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_18.addWidget(self.lineEdit_12)
        self.pushButton_22 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_18.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_18.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_18.addWidget(self.pushButton_24)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 1)
        self.horizontalLayout_18.setStretch(3, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.tableView_2 = QtWidgets.QTableWidget(self.verticalLayoutWidget_6)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_13.addWidget(self.tableView_2)
        self.verticalLayout_13.setStretch(0, 2)
        self.verticalLayout_13.setStretch(1, 6)
        self.stackedWidget_2.addWidget(self.page_3)
        self.horizontalLayout_10.addWidget(self.stackedWidget_2)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 9)

        self.retranslateUi(Form)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_28.setText(_translate("Form", "人脸识别系统"))
        self.groupBox.setTitle(_translate("Form", "功能选项"))
        self.pushButton_sb_3.setText(_translate("Form", "人脸信息录入"))
        self.pushButton_25.setText(_translate("Form", "人脸识别"))
        self.pushButton_gl_3.setText(_translate("Form", "数据库管理"))
        self.pushButton_lr_3.setText(_translate("Form", "退出"))
        self.groupBox_2.setTitle(_translate("Form", "人脸信息录入"))
        self.label_16.setText(_translate("Form", "方式一：图片"))
        self.pushButton_14.setText(_translate("Form", "上传图片"))
        self.label_17.setText(_translate("Form", "方式二：摄像头"))
        self.pushButton_15.setText(_translate("Form", "开启摄像头"))
        self.pushButton_16.setText(_translate("Form", "拍照"))
        self.pushButton_17.setText(_translate("Form", "关闭摄像头"))
        self.label_29.setText(_translate("Form", "人脸信息"))
        self.label_31.setText(_translate("Form", "姓名："))
        self.label_32.setText(_translate("Form", "年龄："))
        self.label_33.setText(_translate("Form", "学号："))
        self.label_34.setText(_translate("Form", "性别："))
        self.radioButton_5.setText(_translate("Form", "男"))
        self.radioButton_6.setText(_translate("Form", "女"))
        self.pushButton_26.setText(_translate("Form", "保存信息"))
        self.groupBox_3.setTitle(_translate("Form", "人脸识别"))
        self.label_25.setText(_translate("Form", "方式一：图片"))
        self.pushButton_19.setText(_translate("Form", "上传图片"))
        self.label_26.setText(_translate("Form", "方式二：摄像头"))
        self.pushButton_20.setText(_translate("Form", "开启摄像头"))
        self.pushButton_21.setText(_translate("Form", "关闭摄像头"))
        self.label_27.setText(_translate("Form", "识别结果"))
        self.groupBox_4.setTitle(_translate("Form", "数据库管理"))
        self.pushButton_22.setText(_translate("Form", "查询"))
        self.pushButton_23.setText(_translate("Form", "删除"))
        self.pushButton_24.setText(_translate("Form", "刷新"))




